# Claude Code Statusline Pro - Storage System Configuration Example
# 存储系统配置示例

# ==================== 基础配置 ====================
preset = "PMBTUS"  # 组件顺序：Project, Model, Branch, Tokens, Usage, Status
theme = "classic"
language = "zh"
debug = false

# ==================== 存储系统配置 ====================
[storage]
# 启用对话级成本追踪
# 当启用时，会追踪整个对话链的所有session，累加显示总成本
enableConversationTracking = true

# 成本显示模式
# - "session": 仅显示当前session的成本
# - "conversation": 显示整个对话链的累加成本
costDisplayMode = "conversation"

# 启用成本数据持久化
# 将每个session的成本数据保存到 ~/.claude/projects/{project}/statusline-pro/sessions/
enableCostPersistence = true

# 自动清理旧会话数据（天数）
# 设置为0禁用自动清理
autoCleanupDays = 30

# ==================== Usage组件配置 ====================
[components.usage]
enabled = true
icon_color = "yellow"
text_color = "white"
emoji_icon = "💰"
nerd_icon = ""
text_icon = "[$]"

# 显示模式
# - "cost": 仅显示成本 "$0.05"
# - "cost_with_lines": 显示成本和代码行数 "$0.05 +12 -5"
# - "cost_with_conversation": 显示对话级累加成本 "$0.05 (3 sessions)"
display_mode = "cost_with_conversation"

# 数值精度（小数位数）
precision = 3

# 显示添加的代码行数
show_lines_added = true

# 显示删除的代码行数
show_lines_removed = true

# ==================== 配置层级说明 ====================
# 配置文件优先级（从高到低）：
# 1. 项目目录下的 config.toml
# 2. ~/.claude/projects/{project}/statusline-pro/config.toml (项目级配置)
# 3. ~/.claude/statusline-pro/config.toml (用户级配置)
# 4. 内置默认配置

# ==================== 文件存储结构 ====================
# ~/.claude/
# ├── statusline-pro/              # 用户级配置目录
# │   └── config.toml              # 用户级配置文件
# │
# └── projects/{project-hash}/
#     └── statusline-pro/          # 项目级配置目录
#         ├── config.toml          # 项目级配置文件
#         └── sessions/            # 会话成本数据目录
#             ├── {sessionId1}.json
#             ├── {sessionId2}.json
#             └── ...