preset = "PMBTUS"
theme = "classic"
language = "zh"
debug = false

[terminal]
force_nerd_font = false
force_emoji = false
force_text = false

[style]
separator = "|"
enable_colors = true
enable_emoji = true
enable_nerd_font = true
separator_color = "white"
separator_before = " "
separator_after = " "
compact_mode = false
max_width = 120

[themes.classic]
enable_gradient = true
ignore_separator = false
fine_progress = false
capsule_style = false

[themes.powerline]
enable_gradient = true
ignore_separator = false
fine_progress = true
capsule_style = false

[themes.capsule]
enable_gradient = true
ignore_separator = true
fine_progress = true
capsule_style = true

[components]
order = ["project", "model", "branch", "tokens", "usage", "status"]

[components.project]
enabled = true
icon_color = "blue"
text_color = "white"
emoji_icon = "📁"
nerd_icon = ""
text_icon = "[P]"
show_when_empty = false

[components.model]
enabled = true
icon_color = "cyan"
text_color = "white"
emoji_icon = "🤖"
nerd_icon = ""
text_icon = "[M]"
show_full_name = false

[components.model.mapping]
claude-sonnet-4 = "S4"
"claude-opus-4.1" = "O4.1"
"claude-haiku-3.5" = "H3.5"

[components.branch]
enabled = true
icon_color = "green"
text_color = "white"
emoji_icon = "🌿"
nerd_icon = ""
text_icon = "[B]"
show_when_no_git = false
max_length = 15

[components.branch.status]
show_dirty = true
show_ahead_behind = true
show_stash_count = true

[components.tokens]
enabled = true
icon_color = "yellow"
text_color = "white"
emoji_icon = "📊"
nerd_icon = ""
text_icon = "[T]"
show_gradient = true
show_progress_bar = true
show_percentage = true
show_raw_numbers = false
progress_width = 15

[components.tokens.progress_bar_chars]
filled = "█"
empty = "░"
backup = "▓"

[components.tokens.colors]
safe = "green"
warning = "yellow"
danger = "red"

[components.tokens.thresholds]
warning = 60
danger = 85
backup = 85
critical = 95

[components.tokens.status_icons.emoji]
backup = "⚡"
critical = "🔥"

[components.tokens.status_icons.nerd]
backup = ""
critical = ""

[components.tokens.status_icons.text]
backup = "[!]"
critical = "[X]"

[components.tokens.context_windows]
default = 200_000
claude-sonnet-4 = 200_000
"claude-opus-4.1" = 200_000
"claude-haiku-3.5" = 200_000

[components.usage]
enabled = true
icon_color = "cyan"
text_color = "white"
emoji_icon = "💰"
nerd_icon = ""
text_icon = "[$]"
precision = 2
display_mode = "cost_with_lines"
show_lines_added = true
show_lines_removed = false

[components.status]
enabled = true
icon_color = "magenta"
text_color = "white"
emoji_icon = "✨"
nerd_icon = ""
text_icon = "[S]"
show_recent_errors = true

[components.status.icons.emoji]
ready = "✅"
thinking = "💭"
tool = "🔧"
error = "❌"
warning = "⚠️"

[components.status.icons.nerd]
ready = ""
thinking = ""
tool = ""
error = ""
warning = ""

[components.status.icons.text]
ready = "[OK]"
thinking = "[...]"
tool = "[TOOL]"
error = "[ERR]"
warning = "[WARN]"

[components.status.colors]
ready = "green"
thinking = "yellow"
tool = "blue"
error = "red"
warning = "yellow"

[preset_mapping]
P = "project"
M = "model"
B = "branch"
T = "tokens"
U = "usage"
S = "status"

[advanced]
cache_enabled = true
recent_error_count = 5
git_timeout = 1_000
custom_color_codes = {}

[experimental]
enable_experimental = false
